- name: Ensure remote .ssh directory exists
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Read local public key
  local_action:
    module: slurp
    src: "~/.ssh/id_rsa.pub"
  register: pub_key_content

- name: Add public key to remote authorized_keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ pub_key_content['content'] | b64decode }}"
    state: present
