global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.148.0.57:9100']
        labels:
          name: staffme-wp-live
      - targets: ['10.148.15.192:9100']
        labels:
          name: staffme-wp-staging