global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '10.148.0.57:9100'
          # - 'ansible-managed-node:9100'
          # - 'traffic-feeder-qa:9100'