global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          # - 'ansible-managed-node:9100'
          # - 'traffic-feeder-qa:9100'
          - 'staffme-wp-server:9100'