---
- name: Create Promtail config directory
  file:
    path: /etc/promtail
    state: directory
    mode: '0755'

- name: Copy Promtail config
  template:
    src: promtail-config.yml.j2
    dest: /etc/promtail/promtail-config.yml
  notify: Restart Promtail

- name: Ensure unzip is installed
  become: true
  package:
    name: unzip
    state: present

- name: Download Promtail binary
  get_url:
    url: https://github.com/grafana/loki/releases/latest/download/promtail-linux-amd64.zip
    dest: /tmp/promtail-linux-amd64.zip

- name: Unzip Promtail binary
  unarchive:
    src: /tmp/promtail-linux-amd64.zip
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/promtail-linux-amd64

- name: Rename and set permissions
  command: mv /usr/local/bin/promtail-linux-amd64 /usr/local/bin/promtail
  args:
    creates: /usr/local/bin/promtail

- name: Make Promtail executable
  file:
    path: /usr/local/bin/promtail
    mode: '0755'

- name: Create systemd service for Promtail
  copy:
    dest: /etc/systemd/system/promtail.service
    content: |
      [Unit]
      Description=Promtail Service
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/promtail -config.file=/etc/promtail/promtail-config.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Promtail
  systemd:
    name: promtail
    enabled: yes
    state: started
