---
- name: Update git branch to server
  hosts: wordpress
  become: true
  roles:
    - role: update_git
      vars:
        repo: "git@github.com:skydevsolutionsinc/cs-wordpress-site.git"
        dest: "/home/wordpress/cs-wordpress-site"
        branch: "feature/docker"
